config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index', as: 'home'
  get '/admin', to: 'admin#index', as: 'admin_home'
  resources :offers, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :advertiser_name, :url, :description, :starts_at, presence: true

  def status
    starts_at <= Date.today && (ends_at.nil? || ends_at >= Date.today)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @offers = Offer.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticated
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def authenticated
    current_user
    redirect_to new_session_path unless @current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticated
  def index
    @offers = OfferFilter.execute
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def new
    @offer = Offer.new
  end

  def create
    offer = Offer.new(offers_params)
    if offer.save
      redirect_to admin_home_path, flash: { success: 'Offer created successefully' }
    else
      redirect_to new_offer_path, flash: { danger: 'You must fill fileds with *' }
    end
  end

  private

  def offers_params
    params.require(:offer).permit(:advertiser_name,
                                  :url,
                                  :description,
                                  :starts_at,
                                  :ends_at,
                                  :premium)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticated
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_home_path, flash: { success: 'user logged' }
    else
      redirect_to new_session_url, flash: { danger: 'User/Password invalid' }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to admin_home_url, notice: 'Logged out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>

<section>
  <h1>Offers</h1>
  <%= link_to "New Offer", new_offer_path,  class: "btn btn-primary" %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Id</th>
      <th>name</th>
      <th>Url</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
    </thead >
    <tbody id="tableTasks">
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.id %></td>
        <td><%= offer.advertiser_name %></td>
        <td><%= offer.url %></td>
        <td><%= offer.status ? 'Enabled' : 'Disabled' %>
        </td>
        <td>
            <%= link_to "Edit", edit_offer_url(offer), class: 'btn btn-info' %>
          <%= link_to "#{offer.status ? 'disable' : 'Enabled' }", edit_offer_url(offer), class: 'btn btn-info' %>
          <%= link_to 'Destroy', edit_offer_path(offer), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'%>
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/home/_card-detail.html.erb
<%= javascript_pack_tag 'home' %>
<script>
    time_tiking(String(<%= offer.id%>), <%= offer.ends_at.end_of_day.to_json.html_safe %>)
</script>
<div class="main-card-offer" id="offer_id_<%= offer.id%>">
  <div class="offer-count-time">
    <table>
      <tr>
        <td>Days</td>
        <td>hours</td>
        <td>Mins</td>
        <td>Secs</td>
      </tr>
      <tr>
        <td id="days_<%= offer.id%>"></td>
        <td id="hours_<%= offer.id%>"></td>
        <td id="mins_<%= offer.id%>"></td>
        <td id="secs_<%= offer.id%>"></td>
      </tr>
    </table>
  </div>
  <% if offer.premium %>
    <p class="main-card-offer-tag">Premium</p>  
  <% end%>
  <h1>
    <%= offer.advertiser_name%>
  </h1>
  <a href="<%= offer.url %>">Shop Now</a>
</div>

app/views/home/index.html.erb
<div class="container-flex">
  <% @offers.each do |offer| %>
    <%= render  partial: 'card-detail', locals: { offer: offer } %>
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashbackService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |type, msg| %>
          <%= bootstrap_flash %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= f.label :advertiser_name, 'Advertiser name *'%>
<%= f.text_field :advertiser_name, class: 'form-control'%>
<%= f.label :url, 'Url *'%>
<%= f.url_field :url, class: 'form-control'%>
<%= f.label :description, 'Description *'%>
<%= f.text_area :description, class: 'form-control'%>
<%= f.label :starts_at, 'Starts at *'%>
<%= f.date_field :starts_at, class: 'form-control'%>
<%= f.label :ends_at, 'End at'%>
<%= f.date_field :ends_at, class: 'form-control'%>
<%= f.check_box :premium, class: ''%>
<%= f.label :premium, 'Premium' %>

app/views/offers/new.html.erb
<h1>New Offer</h1>
<%= link_to "Offers List", admin_home_path%>
<%= form_with model: @offer, class: "nifty_form" do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <br>
  <%= f.submit "Enviar", class: "btn btn-primary" %>
<% end %>